/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twer' at '1/21/15 7:19 AM' with Gradle 2.2.1
 *
 * @author twer, @date 1/21/15 7:19 AM
 */
public class FizzBuzzPlayer {
}
