import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'twer' at '1/21/15 7:19 AM' with Gradle 2.2.1
 *
 * @author twer, @date 1/21/15 7:19 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    // TODO: the player should say the number if the number is normal
    // TODO: the player should say fizz if the number is a multiple of 3 but not a multiple of 15
    // TODO: the player should say buzz if the number is a multiple of 5 but not a multiple of 15
    // TODO: the player should say fizzbuzz if the number is both a multiple of 3 and a multiple of 5
}
